export const FETCH_GRAPH_DATA_REQUEST = 'FETCH_GRAPH_DATA_REQUEST';
export const FETCH_GRAPH_DATA_SUCCESS = 'FETCH_GRAPH_DATA_SUCCESS';
export const FETCH_GRAPH_DATA_FAILURE = 'FETCH_GRAPH_DATA_FAILURE';